### ISSUE TITLE
Add CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by danhenriquesc** [danhenriquesc/hackerrank#25]
Add CONTRIBUTORS.md file with the list of contributors of this project.

Preferentially:
- Sorted alphabetically

Any suggestions are welcome!

**Comment by jackey8616** [comment]
@danhenriquesc  I'd like to take this!

**Comment by nikhilbansal97** [comment]
I want to work on this!

**Comment by jackey8616** [comment]
@danhenriquesc i only add current contributors in repo's [Insights](https://github.com/danhenriquesc/hackerrank/graphs/contributors) page.

**Comment by mukul-kgp** [comment]
I'd Like to work on this

**Comment by danhenriquesc** [comment]
Thank you everyone!
@jackey8616 is working on that, but there is other interesting issues to help :smile:

**Comment by danhenriquesc** [comment]
Merged: https://github.com/danhenriquesc/hackerrank/pull/27
